1.1 EJERCICIO MODULO 3 NUMPY

# Ejercicios

1.  Genera un *array* bidimensional de 4 x 3 con valores aleatorios enteros entre el 34 y el 98. Una vez creado cada array comprueba las dimensiones y los tipos de datos que tenemos en el array. 

2. Crea dos *arrays* (unidimensional, bidimensional) usando el método `np.array()`. 

    Las listas para crear los *arrays* son las siguientes

    ```python
    lista1 = [34,56,71,98, 10]
    lista2 = [[23,45,89, 56], [12,43,82,44]]
    ```

    **Bonus** Haz una pequeña descripción de cada *array* usando los métodos de exploración de *arrays* que hemos aprendido.


In [1]:
# importando librerias
import numpy as np

In [2]:
""" 1.  Genera un array bidimensional de 4 x 3 con valores aleatorios enteros entre el 34 y el 98. Una vez creado cada array comprueba
las dimensiones y los tipos de datos que tenemos en el array."""

# Generar un array bidimensional de 4x3 con valores aleatorios entre 34 y 98
array_aleatorio = np.random.randint(34, 99, size=(4, 3))

# Comprobar las dimensiones del array
dimensiones = array_aleatorio.shape

# Comprobar el tipo de dato del array
tipo_dato = array_aleatorio.dtype

# Imprimir el array generado, dimensiones y tipo de dato
print("Array generado:")
print(array_aleatorio)
print("Dimensiones del array:", dimensiones)
print("Tipo de dato del array:", tipo_dato)

Array generado:
[[73 80 74]
 [52 69 98]
 [83 63 71]
 [68 65 66]]
Dimensiones del array: (4, 3)
Tipo de dato del array: int32


In [3]:
"""
2.Crea dos arrays (unidimensional, bidimensional) usando el método `np.array()`. 

    Las listas para crear los *arrays* son las siguientes

    ```python
    lista1 = [34,56,71,98, 10]
    lista2 = [[23,45,89, 56], [12,43,82,44]]
    ```

    **Bonus** Haz una pequeña descripción de cada array usando los métodos de exploración de arrays que hemos aprendido.

"""

# Listas para crear los arrays
lista1 = [34, 56, 71, 98, 10]
lista2 = [[23, 45, 89, 56], [12, 43, 82, 44]]

# Crear el array unidimensional
array_unidimensional = np.array(lista1)

# Crear el array bidimensional
array_bidimensional = np.array(lista2)

print("descripcion del array unidimensional")
print("-----------------------------------------")
print(f"El array unidimensional es: \n  {array_unidimensional}")
print(f"La forma del array unidimensional es: {array_unidimensional.shape}")
print(f"El número de dimensiones del array unidimensional es: {array_unidimensional.ndim}")
print(f"El número de elementos del array unidimensional es: {array_unidimensional.size}")
print(f"El tipo de dato que tenemos en el array unidimensional es: {array_unidimensional.dtype}\n")
print()
print("-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-")
print()
print("descripcion del array bidimensional")
print("-----------------------------------------")
print(f"El array bidimensional es: \n  {array_bidimensional}")
print(f"La forma del array bidimensional es: {array_bidimensional.shape}")
print(f"El número de dimensiones del array bidimensional es: {array_bidimensional.ndim}")
print(f"El número de elementos del array bidimensional es: {array_bidimensional.size}")
print(f"El tipo de dato que tenemos en el array bidimensional es: {array_bidimensional.dtype}\n")

descripcion del array unidimensional
-----------------------------------------
El array unidimensional es: 
  [34 56 71 98 10]
La forma del array unidimensional es: (5,)
El número de dimensiones del array unidimensional es: 1
El número de elementos del array unidimensional es: 5
El tipo de dato que tenemos en el array unidimensional es: int32


-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-

descripcion del array bidimensional
-----------------------------------------
El array bidimensional es: 
  [[23 45 89 56]
 [12 43 82 44]]
La forma del array bidimensional es: (2, 4)
El número de dimensiones del array bidimensional es: 2
El número de elementos del array bidimensional es: 8
El tipo de dato que tenemos en el array bidimensional es: int32



1.2 EJERCICIO MODULO 3 INDEXACION

3. Crea un *array* unidimensional con 50 elementos con el método que prefieras y extrae: 

    - El primer elemento.


    - Lo elementos que están en posición impar.


    - Los cuatro primeros elementos.


    - Los últimos tres elementos.


    - Los elementos entre el 4 y el 8 (incluido). 

4. Crea un *array* de dos dimensiones de 4 x 5 con el método que prefieras y extrae:

    - La primera fila y todas las columnas.


    - Todas las filas pares.


    - La primera columna y todas las filas.


In [4]:
"""
1. Crea un array unidimensional con 50 elementos con el método que prefieras y extrae: 

    - El primer elemento.


    - Lo elementos que están en posición impar.


    - Los cuatro primeros elementos.


    - Los últimos tres elementos.


    - Los elementos entre el 4 y el 8 (incluido). 

"""

# Crear un array unidimensional con 50 elementos
array_50 = np.arange(1, 51)

# Extraer el primer elemento
primer_elemento = array_50[0]

# Extraer los elementos en posiciones impares
elementos_impares = array_50[1::2]

##
## 1 indica el índice de inicio (comienza desde el segundo elemento, ya que los índices en Python empiezan en 0).
## :: es el separador de los parámetros de slicing.
## 2 es el paso, lo que significa que se selecciona cada segundo elemento a partir del índice de inicio.
## En resumen, array_50[1::2] selecciona todos los elementos de array_50 que están en posiciones impares (segundo, cuarto, sexto, etc.)

# Extraer los cuatro primeros elementos
primeros_cuatro = array_50[:4]

# Extraer los últimos tres elementos
ultimos_tres = array_50[-3:]

# Extraer los elementos entre el 4 y el 8 (incluidos)
entre_4_y_8 = array_50[4:9]

# Imprimir los resultados
print("Primer elemento:", primer_elemento)
print("Elementos en posiciones impares:", elementos_impares)
print("Cuatro primeros elementos:", primeros_cuatro)
print("Últimos tres elementos:", ultimos_tres)
print("Elementos entre el 4 y el 8 (incluidos):", entre_4_y_8)

Primer elemento: 1
Elementos en posiciones impares: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
Cuatro primeros elementos: [1 2 3 4]
Últimos tres elementos: [48 49 50]
Elementos entre el 4 y el 8 (incluidos): [5 6 7 8 9]


In [5]:
"""
    2. Crea un array de dos dimensiones de 4 x 5 con el método que prefieras y extrae:

    - La primera fila y todas las columnas.


    - Todas las filas pares.


    - La primera columna y todas las filas.
"""

# Crear un array bidimensional de 4x5 usando el metodo random.randint()
array_2d = np.random.randint(0, 50, (4,5))

# Extraer la primera fila y todas las columnas
primera_fila_todas_columnas = array_2d[0, :]

# Extraer todas las filas pares
todas_filas_pares = array_2d[::2, :]

# Extraer la primera columna y todas las filas
primera_columna_todas_filas = array_2d[:, 0]

# Imprimir los resultados
print("mi array 2D es:",array_2d)

print("\nPrimera fila y todas las columnas:",primera_fila_todas_columnas)

print("\nTodas las filas pares:", todas_filas_pares)

print("\nPrimera columna y todas las filas:",primera_columna_todas_filas)


mi array 2D es: [[22 32 13 30 32]
 [40 43 48 49 22]
 [33 46 19 49  7]
 [20 41 20 39 44]]

Primera fila y todas las columnas: [22 32 13 30 32]

Todas las filas pares: [[22 32 13 30 32]
 [33 46 19 49  7]]

Primera columna y todas las filas: [22 40 33 20]


## FILTRADO

5. Crea un *array* bidimensional con 20 elementos aleatrorios entre 0 y 50 con el método que prefieras y: 

    - Crea una mascara o filtro donde los valores mayores a 30 y menores a 10 se reemplace por "objetivo" y el resto por "no es mi objetivo".


    - Los valores de mi array bidimensional multiplicalos por el escalar 10.


6. Crea un nuevo *array* de dos dimensiones con la misma forma que el anterior y con el método que prefieras y realiz lo siguiente:

    - Suma el primer array con el segundo.


    - Aplicar la potencia para el primer array elevado al segundo.

In [6]:
"""
1. Crea un *array* bidimensional con 20 elementos aleatrorios entre 0 y 50 con el método que prefieras y: 

    - Crea una mascara o filtro donde los valores mayores a 30 y menores a 10 se reemplace por "objetivo" y el resto por "no es mi objetivo".


    - Los valores de mi array bidimensional multiplicalos por el escalar 10.
"""

# creando mi array de 20 elementos aleatorios entre 0 y 50
array = np.random.randint(0, 51, size=(4, 5))
print("mi array")
print(array)

# creando la mascara
mascara = np.where((array > 30) | (array < 10), "objetivo", "no es mi objetivo")
print("\nMáscara:")
print(mascara)

# Multiplicar el array original por el escalar 10
array_mult = array * 10
print("\nArray multiplicado por 10:")
print(array_mult)

mi array
[[10 27 11 30  4]
 [31 17 24 18 17]
 [25 19 44 42 18]
 [ 3 45 38 21 42]]

Máscara:
[['no es mi objetivo' 'no es mi objetivo' 'no es mi objetivo'
  'no es mi objetivo' 'objetivo']
 ['objetivo' 'no es mi objetivo' 'no es mi objetivo' 'no es mi objetivo'
  'no es mi objetivo']
 ['no es mi objetivo' 'no es mi objetivo' 'objetivo' 'objetivo'
  'no es mi objetivo']
 ['objetivo' 'objetivo' 'objetivo' 'no es mi objetivo' 'objetivo']]

Array multiplicado por 10:
[[100 270 110 300  40]
 [310 170 240 180 170]
 [250 190 440 420 180]
 [ 30 450 380 210 420]]


In [7]:
"""
2. Crea un nuevo *array* de dos dimensiones con la misma forma que el anterior y con el método que prefieras y realiza lo siguiente:

    - Suma el primer array con el segundo.


    - Aplicar la potencia para el primer array elevado al segundo.
"""

# Crear un nuevo array bidimensional con la misma forma
nuevo_array = np.random.randint(0, 51, size=(4, 5))
print("Nuevo array:\n", nuevo_array)

print("-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-")

# mostrar el primer array
print("Primer array:\n", array)

print("-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-")

# Sumar el primer array con el segundo
suma_arrays = array + nuevo_array
print("Suma de los arrays:\n", suma_arrays)

print("-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-")

# Aplicar la potencia del primer array elevado al segundo
potencia_arrays = np.power(array, nuevo_array) # otra forma seria: potencia_arrayas = array ** nuevo_array
print("Potencia del primer array elevado al segundo:\n", potencia_arrays)

Nuevo array:
 [[28  4 24  8 28]
 [ 0 39 36 14  7]
 [21 26 33 24 50]
 [48 12 26 33 26]]
-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
Primer array:
 [[10 27 11 30  4]
 [31 17 24 18 17]
 [25 19 44 42 18]
 [ 3 45 38 21 42]]
-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
Suma de los arrays:
 [[38 31 35 38 32]
 [31 56 60 32 24]
 [46 45 77 66 68]
 [51 57 64 54 68]]
-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
Potencia del primer array elevado al segundo:
 [[  268435456      531441 -1352778207 -1029996288           0]
 [          1    56170353           0 -1614004224   410338673]
 [ -987171207  -317788727           0   553648128           0]
 [  -88328767  -629896911   603979776  1734506389  1677721600]]


Hay valores en cero por desbordamiento del tipo de elemento, en este caso son valores del tipo int32.

1.4 EJERCICIO MODULO 3 FUNCIONES



7. Crea un *array*, puede ser bidimensional! Eso si, los valores tienen que estar entre 0-100

    - Calcula: 

        - La media de los elementos
        - La media de las columnas y redondéalo a dos decimales
        - El valor máximo de cada fila
        - El valor mínimo de cada fila
        - Hay algun valor que sea mayor que 90 en tu *array* 
        - Donde los podemos encontrar, cuáles son sus índices
        - Ordena el *array* de mayor a menor

    📝 **NOTA** En este ejercicio os hemos pedido algunos de los métodos, pero sentiros libres de practicar otros para ir asentando los conocimientos. 

In [8]:
"""
    1. Crea un *array*, puede ser bidimensional! Eso si, los valores tienen que estar entre 0-100

    - Calcula: 

        - La media de los elementos
        - La media de las columnas y redondéalo a dos decimales
        - El valor máximo de cada fila
        - El valor mínimo de cada fila
        - Hay algun valor que sea mayor que 90 en tu *array* 
        - Donde los podemos encontrar, cuáles son sus índices
        - Ordena el *array* de mayor a menor
"""

# Crear un array bidimensional de 5x5 con valores aleatorios entre 0 y 100
array = np.random.randint(0, 101, size=(5, 5))

print("Array original:")
print(array)
print()
print("-----------------------------------------------")
# Calcular la media de todos los elementos del array
media_total = np.mean(array)
print("Media de todos los elementos:", media_total)

print("-----------------------------------------------")
# Calcular la media de cada columna y redondear a dos decimales
media_columnas = np.round(np.mean(array, axis=0), 2)
print("Media de cada columna:")
print(media_columnas)

print("-----------------------------------------------")
# Calcular el valor máximo de cada fila
maximos_filas = np.max(array, axis=1)
print("Valor máximo de cada fila:")
print(maximos_filas)

print("-----------------------------------------------")
# Calcular el valor mínimo de cada fila
minimos_filas = np.min(array, axis=1)
print("Valor mínimo de cada fila:")
print(minimos_filas)

print("-----------------------------------------------")
# Verificar si hay algún valor mayor que 90 en el array
hay_mayor_90 = np.any(array > 90)
print("¿Hay algún valor mayor que 90 en el array?", hay_mayor_90)

# Encontrar los índices de los valores mayores que 90
if hay_mayor_90:
    indices_mayor_90 = np.where(array > 90)
    print("Índices de los valores mayores que 90:")
    print(indices_mayor_90)

print("-----------------------------------------------")
# Ordenar el array de mayor a menor
array_ordenado = np.sort(array.flatten())[::-1] # con el metodo flatten aplanamos el array de dos dimensiones a una sola dimension
print("Array ordenado de mayor a menor:")
print(array_ordenado)

print("-----------------------------------------------")


Array original:
[[69 90  8 70 96]
 [54  8 99 45 32]
 [93 71 65 89 79]
 [ 3 77 87 57 38]
 [73 33 26  7 62]]

-----------------------------------------------
Media de todos los elementos: 57.24
-----------------------------------------------
Media de cada columna:
[58.4 55.8 57.  53.6 61.4]
-----------------------------------------------
Valor máximo de cada fila:
[96 99 93 87 73]
-----------------------------------------------
Valor mínimo de cada fila:
[ 8  8 65  3  7]
-----------------------------------------------
¿Hay algún valor mayor que 90 en el array? True
Índices de los valores mayores que 90:
(array([0, 1, 2], dtype=int64), array([4, 2, 0], dtype=int64))
-----------------------------------------------
Array ordenado de mayor a menor:
[99 96 93 90 89 87 79 77 73 71 70 69 65 62 57 54 45 38 33 32 26  8  8  7
  3]
-----------------------------------------------
